### ISSUE TITLE
Trying to Bind Ingenico Android SDK (Failing!)

### ISSUE THREAD

**Issue by ikymasie** [dikoga/USAePay.iOS.Xamarin#1]
Hi, Im Having an issue binding (Xamarin Android ) to the Ingenico ICMP card reader.... The Binding builds successfully but i get a Java.Lang.NullPointer exception when i try connect.

PLEASE Help!

**Comment by dikoga** [comment]
This bind is specific for Xamarin Android, you will need to create another bind for Android. 

As far as I could google, this is the USAePay library for Android: https://wiki.usaepay.com/developer/android

And here you can see how to bind it to use in your Xamarin project: https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/
